name: Pull Request Lint

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  conventional-commit:
    runs-on: ubuntu-latest
    name: conventional commit check
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: check conventional commit
        id: check-for-cc
        uses: agenthunt/conventional-commit-checker-action@v2.0.0
        with:
          pr-title-regex: '^(?:PROJQUAY-[0-9]+|NO-ISSUE): [a-z]+(?:\([^)]+\))?: .+$'
          pr-body-regex: '(.*)?'
